org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
mod_version=5.0.0
mod_id=ars_trinkets

minecraft_version=1.21.1
parchment_version=2024.07.28
minecraft_version_range=[1.21)
neo_version=21.1.66
neo_version_range=[21.0,)
loader_version_range=[2,)
ars_version=5.3.6.856
jei_version=19.10.0.126
curios_version=9.0.14+1.21.1
geckolib_version=4.6.6
patchouli_version=87-NEOFORGE-SNAPSHOT
caelus_version=7.0.0+1.21

neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.07

mod_group_id=com.c446
mod_name=Ars Trinkets
mod_author=C446
mod_license=MIT
mod_credits=
mod_description=Adds powerful trinkets and spells for ars nouveau.

irons_spells_version=1.21-3.8.4
minecraftVersion=1.21
minecraftVersionRange=[1.21,1.21.1)
neoVersion=21.0.167
neoVersionRange=[21.0.0-beta,)
loaderVersionRange=[4,)

gson_version=2.10.1