modLoader="javafml" #mandatory
loaderVersion="[2,)" #mandatory (28 is current forge version)
license="GNU Lesser General Public License v3.0"
[[mods]] #mandatory
modId="ars_trinkets" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Ars Trinkets" #mandatory
credits="A bunch of Starbuncles"
authors="C446"
description='''
All the power you would ever want from ars nouveau.
'''
# enumExtensions="META-INF/enumextensions.json # NO ENUM EXTENSIONS IN THIS MOD

[[accessTransformers]]
file="META-INF/accesstransformer.cfg" # for potion effects and constructors

[[mixins]]
config="ars_trinkets.mixins.json" # for extra glyphs.

[[dependencies.ars_trinkets]]
modId = "minecraft"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ars_trinkets]]
modId = "ars_nouveau"
versionRange = "[1.21.1-5.4,)"
ordering = "AFTER"
side = "BOTH"