modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "GNU Lesser General Public License v3.0"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Ars Trinkets"
credits = "A bunch of Starbuncles"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ars_nouveau"
type = "required"
versionRange = "[1.21.1-5.4,)"
ordering = "AFTER"
side = "BOTH"
